import React from 'react';
import './globals.css';
import type { Metadata } from 'next';
import styles from './page.module.css';
import { Poppins } from 'next/font/google';
import Navbar from '@/app/components/Navbar';
import Footer from '@/app/components/Footer';
import Heading from '@/app/components/Heading';

const poppins = Poppins({
  weight: ['400', '500', '600', '700', '800'],
  display: 'swap',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className={styles.header}>
          <Navbar />
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
